enabled_locales: ["en", "ja"]
client:
  host: "localhost:8080"
valid:
  length:
    name:
      maximum: 50
      minimum: 6
    email:
      maximum: 255
      minimum: 6
    password:
      maximum: 30
      minimum: 6
    contentMicropost:
      maximum: 140
gravatar:
  size: 80
  microposts: 50
session:
    params:
      rememberme: "1"
paginate:
  perpage: 20
  homeMicropost: 5
passreset:
  expiredTime: 2
image:
  size:
    maximum: 5
